name: simple-pipeline-actions
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USER_DOCKER_HUB }}
          password: ${{ secrets.TOKEN_DOCKER_HUB }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          context: .
          push: true
          tags: fabiogazzoni/cicd-simple-pipeline:${{ github.sha }}.fabiogazzoni/cicd-simple-pipeline:${{github.ref_name }}-${{ github.run_number }}

  docker-run-main:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/main')
    name: Run Docker container on main branch
    steps:
      - run: docker run -e BRANCH=main fabiogazzoni/cicd-simple-pipeline:${{ github.sha }}
